name: Exios Admin API CI
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/exios-admin-api
    strategy:
      matrix:
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16.13.1'
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm start